name: summarize-url
version: "1.0"
description: "Fetch a webpage and extract a clean text summary — useful as an AI agent's 'read this page' tool"

input:
  properties:
    url:
      type: string
      description: "URL to summarize"
      required: true
    max_lines:
      type: string
      description: "Max lines of text to extract (default: 100)"
      required: false

output:
  properties:
    title:
      type: string
    text:
      type: string
    word_count:
      type: integer

trigger:
  type: webhook
  path: /skills/summarize-url

steps:
  - name: fetch-page
    connector: http
    action: request
    input:
      url: "${{ input.url }}"
      method: GET
    on_error: abort

  - name: extract-text
    connector: shell
    action: run
    input:
      command: |
        MAX="${{ input.max_lines }}"
        MAX="${MAX:-100}"
        curl -sL '${{ input.url }}' | \
          sed 's/<script[^>]*>.*<\/script>//g; s/<style[^>]*>.*<\/style>//g' | \
          sed 's/<[^>]*>//g' | \
          sed '/^[[:space:]]*$/d' | \
          sed 's/^[[:space:]]*//' | \
          head -n "$MAX"
    on_error: abort

  - name: extract-title
    connector: shell
    action: run
    input:
      command: "curl -sL '${{ input.url }}' | grep -oP '<title[^>]*>\\K[^<]+' | head -1"
    on_error: continue

  - name: word-count
    connector: shell
    action: run
    input:
      command: "echo '${{ steps.extract-text.output.stdout }}' | wc -w | tr -d ' '"
    on_error: continue

  - name: log-result
    connector: log
    action: print
    input:
      message: "Summarized ${{ input.url }}: \"${{ steps.extract-title.output.stdout }}\" (${{ steps.word-count.output.stdout }} words)"
    on_error: skip
